### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by yunshou** [avenirer/CodeIgniter-multilanguage-site#1]
A Database Error Occurred
Error Number: 1054
Unknown column 'ip' in 'field list'
SELECT `ip` FROM `slugs` WHERE `url` = 'ci_app' LIMIT 1
Filename: D:/xampp/htdocs/CI_app/application/core/MY_Model.php
Line Number: 635

---

HI~ Author 
The same problem after clearing cache~
I can not find the solution

Th'x

**Comment by avenirer** [comment]
of course you can't. there is no database... I will upload the ciapp.sql...
