### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by Blue-Heaven** [avenirer/CodeIgniter-multilanguage-site#16]
Hi,

I've come across this error whilst trying out this script....

A PHP Error was encountered

Severity: Parsing Error

Message: syntax error, unexpected '['

Filename: core/MY_Model.php

Line Number: 608

Backtrace:

**Comment by avenirer** [comment]
Hello... this may be related to the php version you have set up... Anyway... you can download the latest version of MY_Model from here: https://github.com/avenirer/CodeIgniter-MY_Model
