### ISSUE TITLE
I have a question about Rake

### ISSUE THREAD

**Issue by alicansoysal** [avenirer/CodeIgniter-multilanguage-site#18]
Hi,

What is rake and what it is using for? Is it related with dictionary?

**Comment by avenirer** [comment]
Yes. It is related to dictionary. Rake is a keyword extraction tool that can help a search module to do a database search inside posts and pages. It is taking into consideration a language which is having words that are changing their form (inflection - https://en.wikipedia.org/wiki/Inflection) depending on their position inside a sentence (languages like romanian - my native language - come to mind).
