### ISSUE TITLE
will you add hmvc to this project?

### ISSUE THREAD

**Issue by ngangchill** [avenirer/CodeIgniter-multilanguage-site#2]
thanks for the nice apps. will you add hmve to this app in future??

what is your plan with this app?

really i like your works. im learning many things from you...

**Comment by ngangchill** [comment]
i logged in with username: "administrator" and password: "password".
 but showing wrong massage though i logged in successfully:  

Incorrect Login

**Comment by avenirer** [comment]
Hello. Thanks for trying it. At least for the moment no HMVC in my mind, as a lot of people tell me that HMVC is not the way to go... The plan is to do a multilanguage site that you can build from the ground up (including the dictionary in the particular languages that the site may be used...)
