### ISSUE TITLE
url duplicate / appends

### ISSUE THREAD

**Issue by dieandere** [avenirer/CodeIgniter-multilanguage-site#21]
hi, 
how can I fix the problem that I can append the same parameters in the url on and on again?
Same thing is, that I can insert a "/" after the url and get the same site.  

for example you are on this site: 
domain.com/testpage 
If I want, I can insert in the url field: "domain.com/testpage/testpage/testpage" and get the same site without redirecting to the original url (domain.com/testpage) 
and that's with all pages or posts urls. 

I can insert a "/" at the end of the url or not (in the browser url field) - I get the same site. 
Thats all duplicate content, for SEO thats not really good - have you got a solution for this?

**Comment by avenirer** [comment]
That is duplicate content only if you have links from within your own website. But you are right. This shouldn't happen. We can defend against this by creating a MY_Router.php, and verify if the method accepts the right number of parameters passed in the URL.
