### ISSUE TITLE
Featured Image Upload

### ISSUE THREAD

**Issue by rexsantos23** [avenirer/CodeIgniter-multilanguage-site#22]
Featured image upload is not working, it's not saving into database.

**Comment by avenirer** [comment]
There was a problem with the image_nation library, which loads the featured image. Could you try again? Or give me more details... At least on my tests it saved the info in the database but the path was wrong.

**Comment by rexsantos23** [comment]
Sorry for the super delayed reply. as im working on another project. The CMS is very simple and easy to understand. will try this soon! Thanks
