### ISSUE TITLE
bug _post_show function

### ISSUE THREAD

**Issue by ang3lx** [avenirer/CodeIgniter-multilanguage-site#24]
**Line 61** (_post_show method) of **/application/controllers/Findcontent.php**
is

`$alternate_content = $this->slug_model->where(array('content_id' => $this->translation->id, 'redirect' => '0'))->get_all();`

should be

`$alternate_content = $this->slug_model->where(array('content_id' => $this->translation->content_id, 'redirect' => '0'))->get_all();`

**Comment by avenirer** [comment]
Thank you.
